name: Create Repositories

on:
  # schedule:
   # - cron: '*/45 * * * *'  # Run every 45 minutes
  workflow_dispatch:  # Trigger manually

jobs:
  create_repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check current time and create repositories
      run: |
        for i in {292..1001}; do
          random_string=$(openssl rand -hex 4)
          repo_name="fuck_you_GarouTheDevil_${random_string}"

          echo "Creating repository $repo_name"

          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.H_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"name":"'"$repo_name"'","private":false}' \
            "https://api.github.com/user/repos")

          if [ $(echo "$response" | jq -r .id) ]; then
            echo "Repository '$repo_name' created successfully."
          else
            echo "Failed to create repository '$repo_name'. Response: $response"
            exit 1  # Exit with an error code to cancel the workflow
          fi
        done
        
